version: '3.0'

services:
  database:
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD:root}
      - POSTGRES_USER=${DB_USER:root}
      - POSTGRES_DB=${DB_DATABASE:postgres}

    ports:
      - 5432:5432
    
    volumes:
      - database:/var/lib/postgresql

    networks:
      - mynetwork

volumes:
  database:
    driver: local

networks:
  mynetwork: 
    driver: bridge